In [1]:
import nltk
import pandas as pd

In [2]:
data = pd.read_csv("/content/English.csv")
data.head()

  English words/sentences
0                     Hi.
1                    Run!
2                    Run!
3                    Who?
4                    Wow!

In [3]:
data.shape

(53123, 1)

In [4]:
data['English words/sentences'] = data['English words/sentences'].str.replace("[^a-zA-Z0-9]", " ")
data.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

  English words/sentences
0                     Hi
1                    Run
2                    Run
3                    Who
4                    Wow

In [5]:
!pip install googletrans==3.1.0a0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googletrans==3.1.0a0
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
Collecting httpx==0.13.3
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.5 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2022.6.15)
Collecting rfc3986<2,>=1.3
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting hstspreload
  Downloading hstspreload-2022.8.1-py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 29.1 MB/s
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (3.0.4)
Collecting httpcore==0.9.*
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.6 MB/s
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2.10)
Collecting h11<0.10,>=0.8
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.8 MB/s
Collecting h2==3.*
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 4.8 MB/s
Collecting hpack<4,>=3.0
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Collecting hyperframe<6,>=5.2.0
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16367 sha256=afe6c3e6fa162dc4874df6bbab5cdcd5a280040c4a6420a87f8b5945e7c06e22
  Stored in directory: /root/.cache/pip/wheels/0c/be/fe/93a6a40ffe386e16089e44dad9018ebab9dc4cb9eb7eab65ae
Successfully built googletrans
Installing collected packages: hyperframe, hpack, sniffio, h2, h11, rfc3986, httpcore, hstspreload, httpx, googletrans
Successfully installed googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2022.8.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 rfc3986-1.5.0 sniffio-1.2.0

In [6]:
from googletrans import Translator
translator = Translator()

In [7]:
spanish=data.head(7000)
spanish.shape

(7000, 1)

In [8]:
spanish["English words/sentences"] = spanish["English words/sentences"].apply(lambda x: translator.translate(x, dest="es").text)
#dt = dt.apply(lambda x: translator.translate(x,dest='es').text)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
spanish.head(10)

  English words/sentences
0                    Hola
1                  Correr
2                  Correr
3                   Quién
4                    Guau
5                   Fuego
6                   Ayuda
7                   Salto
8               Deténgase
9               Deténgase

In [10]:
french = data.head(7000)
french.shape

(7000, 1)

In [11]:
french["English words/sentences"] = french["English words/sentences"].apply(lambda x: translator.translate(x, dest="fr").text)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
french.head()

  English words/sentences
0                   Heure
1                  Courir
2                  Courir
3                     Qui
4                    Ouah

In [13]:
german = data.head(7000)
german.shape

(7000, 1)

In [14]:
german["English words/sentences"] = german["English words/sentences"].apply(lambda x: translator.translate(x, dest="de").text)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
german.head()

  English words/sentences
0                  Stunde
1                  Laufen
2                  Laufen
3                     Wer
4                     Wow

**TASK 2**

In [16]:
dataset = pd.read_csv("/content/aspell.txt")

In [17]:
dataset.columns=['incorrect']

In [18]:
dt=dataset.head(100)
dt

                       incorrect
0     Presbyterian: presbyterian
1                       RSX: rsx
2               Stephen: Steffen
3                   Susan: susan
4              ability: abilitey
..                           ...
95                  croak: croke
96           crucified: crusifed
97     crucifixion: crucifiction
98  customization: custamisation
99                   daily: daly

[100 rows x 1 columns]

In [19]:

wrng = []
crt = []

for i in dt['incorrect']:
  if ':' in i:
    # Splitting the sentence on '|'
    str1 = i.split(':')
    # Previous word to '|' is storing in loriginal list.
    crt.append(str1[0])
    # Next word to '|' is storing in lcorrected list.
    wrng.append(str1[1])

wrng

[' presbyterian',
 ' rsx',
 ' Steffen',
 ' susan',
 ' abilitey',
 ' abouy',
 ' absorbtion',
 ' accidently',
 ' accomodate acommadate',
 ' acord',
 ' aquantance',
 ' equire',
 ' adultry',
 ' aggresive',
 ' alchohol',
 ' alchoholic',
 ' allieve',
 ' alright',
 ' amature',
 ' ambivilant',
 ' amourfous',
 ' amification',
 ' anonomy anotomy',
 ' annuncio',
 ' annonsment',
 ' annoint',
 ' anynomous',
 ' appresteate',
 ' appreceiated',
 ' archeype',
 ' aratictature aricticure',
 ' artic',
 ' asterick',
 ' asymetric',
 ' asentote',
 ' ast',
 ' atentively',
 ' autoamlly',
 ' bankrot',
 ' basicly',
 ' batallion',
 ' beggining beging bigginging',
 ' behaviour',
 ' behavior',
 ' beleive belive',
 ' benidifs',
 ' metter',
 ' blait',
 ' boygot',
 ' brocolli',
 ' bbrose',
 ' bouyant',
 ' beauro',
 ' beaurocracy buracracy burracracy',
 ' buch',
 ' buder budr budter',
 ' buton',
 ' byby',
 ' cauler',
 ' gamne',
 ' cravets',
 ' cemetary',
 ' changeing',
 ' cheet',
 ' cicle circue',
 ' circumstaces',
 ' clob',
 ' cocamena',
 ' colleaque',
 ' colloquilism',
 ' coaln',
 ' columne',
 ' cumba',
 ' commerciasl',
 ' comitmment comittmen comittmend',
 ' commited',
 ' comitte commitee',
 ' companys',
 ' comiler',
 ' compicated',
 ' comupter',
 ' congradulations',
 ' concensus',
 ' consident',
 ' consident',
 ' contast contastant',
 ' contunie',
 ' conibation',
 ' cooly',
 ' copping',
 ' cosmoplyton',
 ' courst',
 ' crasy',
 ' credetability',
 ' criqitue ctitique',
 ' croke',
 ' crusifed',
 ' crucifiction',
 ' custamisation',
 ' daly']

In [20]:
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from collections import Iterable
#def flatten(lis):
#     for item in lis:
#         if isinstance(item, Iterable) and not isinstance(item, str):
#             for x in flatten(item):
#                 yield x
#         else:        
#             yield item

token_list = []
for token in wrng:
    token_list.append(word_tokenize(token))
incorrect_words = [element for innerList in token_list for element in innerList]
#incorrect_words=list(flatten(token_list))
incorrect_words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  This is separate from the ipykernel package so we can avoid doing imports until

['presbyterian',
 'rsx',
 'Steffen',
 'susan',
 'abilitey',
 'abouy',
 'absorbtion',
 'accidently',
 'accomodate',
 'acommadate',
 'acord',
 'aquantance',
 'equire',
 'adultry',
 'aggresive',
 'alchohol',
 'alchoholic',
 'allieve',
 'alright',
 'amature',
 'ambivilant',
 'amourfous',
 'amification',
 'anonomy',
 'anotomy',
 'annuncio',
 'annonsment',
 'annoint',
 'anynomous',
 'appresteate',
 'appreceiated',
 'archeype',
 'aratictature',
 'aricticure',
 'artic',
 'asterick',
 'asymetric',
 'asentote',
 'ast',
 'atentively',
 'autoamlly',
 'bankrot',
 'basicly',
 'batallion',
 'beggining',
 'beging',
 'bigginging',
 'behaviour',
 'behavior',
 'beleive',
 'belive',
 'benidifs',
 'metter',
 'blait',
 'boygot',
 'brocolli',
 'bbrose',
 'bouyant',
 'beauro',
 'beaurocracy',
 'buracracy',
 'burracracy',
 'buch',
 'buder',
 'budr',
 'budter',
 'buton',
 'byby',
 'cauler',
 'gamne',
 'cravets',
 'cemetary',
 'changeing',
 'cheet',
 'cicle',
 'circue',
 'circumstaces',
 'clob',
 'cocamena',
 'colleaque',
 'colloquilism',
 'coaln',
 'columne',
 'cumba',
 'commerciasl',
 'comitmment',
 'comittmen',
 'comittmend',
 'commited',
 'comitte',
 'commitee',
 'companys',
 'comiler',
 'compicated',
 'comupter',
 'congradulations',
 'concensus',
 'consident',
 'consident',
 'contast',
 'contastant',
 'contunie',
 'conibation',
 'cooly',
 'copping',
 'cosmoplyton',
 'courst',
 'crasy',
 'credetability',
 'criqitue',
 'ctitique',
 'croke',
 'crusifed',
 'crucifiction',
 'custamisation',
 'daly']

In [21]:
from nltk.metrics.distance import edit_distance
nltk.download('words')
from nltk.corpus import words
correct_words = words.words()


for word in incorrect_words:
    temp = [(edit_distance(word, w),w) for w in correct_words if w[0]==word[0]]
    print(sorted(temp, key = lambda val:val[0])[0][1])

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

presbyteria
rax
Steen
sasan
ability
abody
absorbition
accidently
accommodate
accommodate
abord
acquaintance
enquire
adultery
aggressive
alcohol
alcoholic
achieve
alright
abature
ambivalent
amorous
actification
agronomy
anatomy
announce
annoyment
anoint
anonymous
appreciate
appreciate
archetype
antestature
arcticize
antic
asterisk
asymmetric
aseptate
ast
attentively
actually
bandrol
basally
battalion
begging
begging
beginning
behaviour
behavior
beleave
belive
bending
matter
bait
bigot
broccoli
brose
boltant
bauno
beerocracy
bureaucracy
bureaucracy
bach
bider
bud
budder
baton
baby
cabler
gaine
crants
cemetery
changeling
cheet
chicle
circle
circumstance
chob
cocamine
colleague
colloquialism
coal
column
cumbha
commercial
commitment
cocitizen
coattend
combined
cocotte
committee
company
coiler
complicated
compter
congratulation
concentus
confident
confident
contact
contestant
continue
cibation
cooly
copping
cosmopolitan
course
crapy
creditability
crinite
critique
choke
crucifer
crucifixion
contamination
daily